### ISSUE TITLE
PHP warning error on article edit

### ISSUE THREAD

**Issue by Eldenroot** [Krytic/MyBBWiki#25]
Latest GitHub version (1.2.0) - when you edit the article, this is shown above the header

![error](https://cloud.githubusercontent.com/assets/778890/20239760/6aa7a838-a908-11e6-8aef-2d16bf986d93.png)

**Comment by Krytic** [comment]
I suspect this is a PHP 7 error which I don't plan to support for a little while. That being said, this should be fixed in the new version coming out in a day or so :)

**Comment by Eldenroot** [comment]
@Krytic - propably yes. My hosting supports only latest php version so I cannot confirm if it php 7 related. Thank you very much!

**Comment by Eldenroot** [comment]
@Krytic - the error is still there (latest GitHub version - 1.2.1pre-release

![error1 2 1](https://cloud.githubusercontent.com/assets/778890/20321275/34c4b2be-ab75-11e6-9421-7e450d1abc95.png)

But, now only one left, in v1.2.0 there were two warnings

**Comment by Eldenroot** [comment]
@Krytic - Hi, any progress? I just need this working :)
